-- Weekly revenue targets maintained at branch level.
-- Monthly branch targets can be derived by summing target_revenue for the
-- same academic_year and month. This table is intentionally separate from
-- agent-level weekly targets and the legacy monthly target table.
create table if not exists public.t_branch_weekly_target (
  id bigint generated by default as identity primary key,
  academic_year text not null,
  month text not null,
  week_start date not null,
  branch_id integer not null,
  target_revenue bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint t_branch_weekly_target_academic_year_fkey foreign key (academic_year)
    references public.t_academic_year (academic_year),
  constraint t_branch_weekly_target_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_branch_weekly_target_week_start_monday_check
    check (extract(isodow from week_start) = 1),
  constraint t_branch_weekly_target_month_format_check
    check (month ~ '^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) [0-9]{4}$'),
  constraint t_branch_weekly_target_branch_excluded_check
    check (branch_id <> 100),
  constraint t_branch_weekly_target_revenue_non_negative
    check (target_revenue >= 0),
  constraint t_branch_weekly_target_branch_week_unique
    unique (branch_id, week_start)
);

create index if not exists t_branch_weekly_target_academic_month_idx
  on public.t_branch_weekly_target (academic_year, month);
create index if not exists t_branch_weekly_target_branch_id_idx
  on public.t_branch_weekly_target (branch_id);
create index if not exists t_branch_weekly_target_week_start_idx
  on public.t_branch_weekly_target (week_start);

alter table public.t_branch_weekly_target enable row level security;

drop trigger if exists set_t_branch_weekly_target_updated_at
  on public.t_branch_weekly_target;
create trigger set_t_branch_weekly_target_updated_at
before update on public.t_branch_weekly_target
for each row execute function public.set_updated_at();

drop policy if exists "authenticated can read branch weekly targets"
  on public.t_branch_weekly_target;
create policy "authenticated can read branch weekly targets"
  on public.t_branch_weekly_target for select
  to authenticated
  using (true);

drop policy if exists "service role can manage branch weekly targets"
  on public.t_branch_weekly_target;
create policy "service role can manage branch weekly targets"
  on public.t_branch_weekly_target for all
  to service_role
  using (true)
  with check (true);
