-- Authentication and administrator activity history for dashboard operations.
create table if not exists public.t_user_login_log (
  id bigint generated by default as identity primary key,
  user_id uuid,
  email text not null,
  logged_in_at timestamp with time zone not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists t_user_login_log_logged_in_at_idx
  on public.t_user_login_log (logged_in_at desc);
create index if not exists t_user_login_log_email_idx
  on public.t_user_login_log (email);

alter table public.t_user_login_log enable row level security;

drop policy if exists "service role can manage user login logs"
  on public.t_user_login_log;
create policy "service role can manage user login logs"
  on public.t_user_login_log for all
  to service_role
  using (true)
  with check (true);

create table if not exists public.t_admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  actor_email text not null,
  action text not null,
  target_type text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

create index if not exists t_admin_audit_log_created_at_idx
  on public.t_admin_audit_log (created_at desc);
create index if not exists t_admin_audit_log_actor_email_idx
  on public.t_admin_audit_log (actor_email);

alter table public.t_admin_audit_log enable row level security;

drop policy if exists "service role can manage admin audit logs"
  on public.t_admin_audit_log;
create policy "service role can manage admin audit logs"
  on public.t_admin_audit_log for all
  to service_role
  using (true)
  with check (true);
