-- Revenue module: transactions, targets, imports, and dashboard analytics.

create or replace function public.revenue_academic_month_number(p_month text)
returns smallint
language sql
immutable
strict
as $$
  select case lower(btrim(p_month))
    when 'jul' then 1
    when 'aug' then 2
    when 'sep' then 3
    when 'oct' then 4
    when 'nov' then 5
    when 'dec' then 6
    when 'jan' then 7
    when 'feb' then 8
    when 'mar' then 9
    when 'apr' then 10
    when 'may' then 11
    when 'jun' then 12
    else null
  end::smallint;
$$;

create or replace function public.revenue_academic_month_label(p_month_number smallint)
returns text
language sql
immutable
strict
as $$
  select case p_month_number
    when 1 then 'Jul'
    when 2 then 'Aug'
    when 3 then 'Sep'
    when 4 then 'Oct'
    when 5 then 'Nov'
    when 6 then 'Dec'
    when 7 then 'Jan'
    when 8 then 'Feb'
    when 9 then 'Mar'
    when 10 then 'Apr'
    when 11 then 'May'
    when 12 then 'Jun'
    else null
  end;
$$;

create table if not exists public.t_revenue_products (
  product_id integer primary key,
  product_code text not null,
  product_name text not null,
  constraint t_revenue_products_product_code_unique unique (product_code),
  constraint t_revenue_products_product_code_not_blank check (btrim(product_code) <> ''),
  constraint t_revenue_products_product_name_not_blank check (btrim(product_name) <> '')
);

create index if not exists t_revenue_products_product_code_idx
on public.t_revenue_products (product_code);

alter table public.t_revenue_products enable row level security;

drop policy if exists "authenticated can read revenue products"
on public.t_revenue_products;
create policy "authenticated can read revenue products"
on public.t_revenue_products for select
to authenticated
using (true);

drop policy if exists "admin can manage revenue products"
on public.t_revenue_products;
create policy "admin can manage revenue products"
on public.t_revenue_products for all
to service_role
using (true)
with check (true);

insert into public.t_revenue_products (product_id, product_code, product_name)
values
  (1, 'BAC', 'Brain Academy Center'),
  (2, 'BAO', 'Brain Academy Online'),
  (3, 'EAC', 'English Academy Center'),
  (4, 'Kalananti', 'Kids Product'),
  (5, 'Others', 'Others'),
  (6, 'MC', 'Math Champs'),
  (7, 'RGP', 'Ruangguru Private'),
  (8, 'Roboguru', 'Roboguru'),
  (9, 'Ruanguji', 'Ruanguji'),
  (10, 'Schoters', 'Schoters'),
  (11, 'RB', 'Ruangbelajar'),
  (12, 'SA', 'Skill Academy')
on conflict (product_id) do update
set
  product_code = excluded.product_code,
  product_name = excluded.product_name;

create table if not exists public.t_revenue_txn (
  id integer generated by default as identity primary key,
  payment_date date not null,
  month text not null,
  invoice text not null,
  grade_id integer,
  product_id integer,
  agent_id integer,
  branch_destination_id integer,
  branch_id integer,
  is_newtxn boolean not null default false,
  is_fullpayment boolean not null default false,
  academic_year text,
  npsn text,
  revenue integer,
  is_bulkbuying boolean not null default false,
  constraint t_revenue_txn_month_format check (
    month ~ '^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) [0-9]{4}$'
  ),
  constraint t_revenue_txn_grade_id_fkey foreign key (grade_id)
    references public.t_grade (grade_id),
  constraint t_revenue_txn_product_id_fkey foreign key (product_id)
    references public.t_revenue_products (product_id),
  constraint t_revenue_txn_agent_id_fkey foreign key (agent_id)
    references public.t_agent (agent_id),
  constraint t_revenue_txn_branch_destination_id_fkey foreign key (branch_destination_id)
    references public.t_branch (branch_id),
  constraint t_revenue_txn_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_revenue_txn_academic_year_fkey foreign key (academic_year)
    references public.t_academic_year (academic_year),
  constraint t_revenue_txn_npsn_fkey foreign key (npsn)
    references public.t_master_school (npsn)
);

create index if not exists t_revenue_txn_payment_date_idx
on public.t_revenue_txn (payment_date);
create index if not exists t_revenue_txn_month_idx
on public.t_revenue_txn (month);
create index if not exists t_revenue_txn_invoice_idx
on public.t_revenue_txn (invoice);
create index if not exists t_revenue_txn_grade_id_idx
on public.t_revenue_txn (grade_id);
create index if not exists t_revenue_txn_product_id_idx
on public.t_revenue_txn (product_id);
create index if not exists t_revenue_txn_agent_id_idx
on public.t_revenue_txn (agent_id);
create index if not exists t_revenue_txn_branch_id_idx
on public.t_revenue_txn (branch_id);
create index if not exists t_revenue_txn_academic_year_idx
on public.t_revenue_txn (academic_year);
create index if not exists t_revenue_txn_npsn_idx
on public.t_revenue_txn (npsn);

alter table public.t_revenue_txn enable row level security;

drop policy if exists "authenticated can read revenue transactions"
on public.t_revenue_txn;
create policy "authenticated can read revenue transactions"
on public.t_revenue_txn for select
to authenticated
using (true);

drop policy if exists "admin can manage revenue transactions"
on public.t_revenue_txn;
create policy "admin can manage revenue transactions"
on public.t_revenue_txn for all
to service_role
using (true)
with check (true);

create or replace function public.replace_revenue_txn_by_dates(p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dates date[];
  v_deleted bigint := 0;
  v_inserted bigint := 0;
begin
  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'p_rows harus berupa JSON array';
  end if;

  select array_agg(distinct x.payment_date order by x.payment_date)
  into v_dates
  from jsonb_to_recordset(p_rows) as x(payment_date date);

  if coalesce(array_length(v_dates, 1), 0) = 0 then
    return jsonb_build_object('replaced_dates', 0, 'deleted_rows', 0, 'inserted_rows', 0);
  end if;

  delete from public.t_revenue_txn
  where payment_date = any(v_dates);
  get diagnostics v_deleted = row_count;

  insert into public.t_revenue_txn (
    payment_date, month, invoice, grade_id, product_id, agent_id,
    branch_destination_id, branch_id, is_newtxn, is_fullpayment,
    academic_year, npsn, revenue, is_bulkbuying
  )
  select
    x.payment_date, x.month, x.invoice, x.grade_id, x.product_id, x.agent_id,
    x.branch_destination_id, x.branch_id, x.is_newtxn, x.is_fullpayment,
    x.academic_year, x.npsn, x.revenue, x.is_bulkbuying
  from jsonb_to_recordset(p_rows) as x(
    payment_date date, month text, invoice text, grade_id integer,
    product_id integer, agent_id integer, branch_destination_id integer,
    branch_id integer, is_newtxn boolean, is_fullpayment boolean,
    academic_year text, npsn text, revenue integer, is_bulkbuying boolean
  );
  get diagnostics v_inserted = row_count;

  return jsonb_build_object(
    'replaced_dates', cardinality(v_dates),
    'deleted_rows', v_deleted,
    'inserted_rows', v_inserted,
    'dates', to_jsonb(v_dates)
  );
end;
$$;

create table if not exists public.t_revenue_annual_target (
  id bigint generated by default as identity primary key,
  academic_year text not null,
  branch_id integer not null,
  target_revenue bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint t_revenue_annual_target_revenue_non_negative check (target_revenue >= 0),
  constraint t_revenue_annual_target_academic_year_fkey foreign key (academic_year)
    references public.t_academic_year (academic_year),
  constraint t_revenue_annual_target_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_revenue_annual_target_unique unique (academic_year, branch_id)
);

create table if not exists public.t_revenue_monthly_target (
  id bigint generated by default as identity primary key,
  academic_year text not null,
  branch_id integer not null,
  month_number smallint not null,
  target_revenue bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint t_revenue_monthly_target_month_number_check check (month_number between 1 and 12),
  constraint t_revenue_monthly_target_revenue_non_negative check (target_revenue >= 0),
  constraint t_revenue_monthly_target_academic_year_fkey foreign key (academic_year)
    references public.t_academic_year (academic_year),
  constraint t_revenue_monthly_target_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_revenue_monthly_target_unique unique (academic_year, branch_id, month_number)
);

create index if not exists t_revenue_annual_target_academic_year_idx
on public.t_revenue_annual_target (academic_year);
create index if not exists t_revenue_annual_target_branch_id_idx
on public.t_revenue_annual_target (branch_id);
create index if not exists t_revenue_monthly_target_academic_year_idx
on public.t_revenue_monthly_target (academic_year);
create index if not exists t_revenue_monthly_target_branch_id_idx
on public.t_revenue_monthly_target (branch_id);

alter table public.t_revenue_annual_target enable row level security;
alter table public.t_revenue_monthly_target enable row level security;

drop trigger if exists set_t_revenue_annual_target_updated_at on public.t_revenue_annual_target;
create trigger set_t_revenue_annual_target_updated_at
before update on public.t_revenue_annual_target
for each row execute function public.set_updated_at();

drop trigger if exists set_t_revenue_monthly_target_updated_at on public.t_revenue_monthly_target;
create trigger set_t_revenue_monthly_target_updated_at
before update on public.t_revenue_monthly_target
for each row execute function public.set_updated_at();

drop policy if exists "authenticated can read annual revenue targets"
on public.t_revenue_annual_target;
create policy "authenticated can read annual revenue targets"
on public.t_revenue_annual_target for select to authenticated using (true);

drop policy if exists "admin can manage annual revenue targets"
on public.t_revenue_annual_target;
create policy "admin can manage annual revenue targets"
on public.t_revenue_annual_target for all to service_role
using (true) with check (true);

drop policy if exists "authenticated can read monthly revenue targets"
on public.t_revenue_monthly_target;
create policy "authenticated can read monthly revenue targets"
on public.t_revenue_monthly_target for select to authenticated using (true);

drop policy if exists "admin can manage monthly revenue targets"
on public.t_revenue_monthly_target;
create policy "admin can manage monthly revenue targets"
on public.t_revenue_monthly_target for all to service_role
using (true) with check (true);

create or replace view public.v_revenue_annual_target_by_region
with (security_invoker = true)
as
select
  t.academic_year,
  b.region_id,
  r.region_name,
  sum(t.target_revenue)::bigint as target_revenue
from public.t_revenue_annual_target t
join public.t_branch b on b.branch_id = t.branch_id
join public.t_region r on r.region_id = b.region_id
group by t.academic_year, b.region_id, r.region_name;

create or replace view public.v_revenue_monthly_target_by_region
with (security_invoker = true)
as
select
  t.academic_year,
  t.month_number,
  b.region_id,
  r.region_name,
  sum(t.target_revenue)::bigint as target_revenue
from public.t_revenue_monthly_target t
join public.t_branch b on b.branch_id = t.branch_id
join public.t_region r on r.region_id = b.region_id
group by t.academic_year, t.month_number, b.region_id, r.region_name;

create or replace view public.v_revenue_annual_target_summary
with (security_invoker = true)
as
select academic_year, sum(target_revenue)::bigint as target_revenue
from public.t_revenue_annual_target
group by academic_year;

create or replace view public.v_revenue_monthly_target_summary
with (security_invoker = true)
as
select academic_year, month_number, sum(target_revenue)::bigint as target_revenue
from public.t_revenue_monthly_target
group by academic_year, month_number;

create or replace function public.import_revenue_annual_targets(p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_imported bigint := 0;
begin
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'p_rows harus berupa JSON array'; end if;
  insert into public.t_revenue_annual_target (academic_year, branch_id, target_revenue)
  select x.academic_year, x.branch_id, x.target_revenue
  from jsonb_to_recordset(p_rows) as x(
    academic_year text, branch_id integer, target_revenue bigint
  )
  on conflict (academic_year, branch_id) do update
  set target_revenue = excluded.target_revenue, updated_at = now();
  get diagnostics v_imported = row_count;
  return jsonb_build_object('imported_rows', v_imported);
end;
$$;

create or replace function public.import_revenue_monthly_targets(p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_imported bigint := 0;
begin
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'p_rows harus berupa JSON array'; end if;
  insert into public.t_revenue_monthly_target (
    academic_year, branch_id, month_number, target_revenue
  )
  select
    x.academic_year,
    x.branch_id,
    public.revenue_academic_month_number(x.month),
    x.target_revenue
  from jsonb_to_recordset(p_rows) as x(
    academic_year text, branch_id integer, month text, target_revenue bigint
  )
  on conflict (academic_year, branch_id, month_number) do update
  set target_revenue = excluded.target_revenue, updated_at = now();
  get diagnostics v_imported = row_count;
  return jsonb_build_object('imported_rows', v_imported);
end;
$$;

create or replace function public.get_revenue_dashboard_v2(
  p_academic_year text default null,
  p_region_id integer default null,
  p_branch_id integer default null,
  p_month text default null,
  p_from_date date default null,
  p_to_date date default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_current_year text := coalesce(
    p_academic_year,
    (select academic_year from public.t_academic_year where is_active order by academic_year desc limit 1)
  );
  v_ly_year text;
  v_l2y_year text;
  v_start_date date;
  v_end_date date;
  v_ly_start date;
  v_ly_end date;
  v_l2y_start date;
  v_l2y_end date;
  v_month_number smallint;
  v_target numeric := 0;
  v_current numeric := 0;
  v_ly numeric := 0;
  v_l2y numeric := 0;
  v_result jsonb;
begin
  v_ly_year := lpad(((split_part(v_current_year, '/', 1)::integer + 99) % 100)::text, 2, '0')
    || '/' || split_part(v_current_year, '/', 1);
  v_l2y_year := lpad(((split_part(v_current_year, '/', 1)::integer + 98) % 100)::text, 2, '0')
    || '/' || lpad(((split_part(v_current_year, '/', 1)::integer + 99) % 100)::text, 2, '0');
  if not exists (select 1 from public.t_academic_year where academic_year = v_ly_year) then v_ly_year := null; end if;
  if not exists (select 1 from public.t_academic_year where academic_year = v_l2y_year) then v_l2y_year := null; end if;

  v_start_date := make_date(2000 + split_part(v_current_year, '/', 1)::integer, 7, 1);
  v_end_date := make_date(2000 + split_part(v_current_year, '/', 2)::integer, 6, 30);

  if p_month is not null then
    v_month_number := public.revenue_academic_month_number(p_month);
    if v_month_number is null then raise exception 'Bulan tidak valid: %', p_month; end if;
    v_start_date := make_date(
      case when v_month_number <= 6 then 2000 + split_part(v_current_year, '/', 2)::integer
           else 2000 + split_part(v_current_year, '/', 1)::integer end,
      case when v_month_number <= 6 then v_month_number + 6 else v_month_number - 6 end,
      1
    );
    v_end_date := (date_trunc('month', v_start_date) + interval '1 month - 1 day')::date;
  end if;

  v_start_date := greatest(v_start_date, coalesce(p_from_date, v_start_date));
  v_end_date := least(v_end_date, coalesce(p_to_date, v_end_date));
  v_ly_start := (v_start_date - interval '1 year')::date;
  v_ly_end := (v_end_date - interval '1 year')::date;
  v_l2y_start := (v_start_date - interval '2 years')::date;
  v_l2y_end := (v_end_date - interval '2 years')::date;

  select
    coalesce(sum(tx.revenue) filter (where tx.academic_year = v_current_year and tx.payment_date between v_start_date and v_end_date), 0),
    coalesce(sum(tx.revenue) filter (where v_ly_year is not null and tx.academic_year = v_ly_year and tx.payment_date between v_ly_start and v_ly_end), 0),
    coalesce(sum(tx.revenue) filter (where v_l2y_year is not null and tx.academic_year = v_l2y_year and tx.payment_date between v_l2y_start and v_l2y_end), 0)
  into v_current, v_ly, v_l2y
  from public.t_revenue_txn tx
  join public.t_branch b on b.branch_id = tx.branch_id
  where (tx.payment_date between v_start_date and v_end_date
    or tx.payment_date between v_ly_start and v_ly_end
    or tx.payment_date between v_l2y_start and v_l2y_end)
    and (p_region_id is null or b.region_id = p_region_id)
    and (p_branch_id is null or tx.branch_id = p_branch_id);

  select coalesce(sum(t.target_revenue), 0)
  into v_target
  from public.t_revenue_annual_target t
  join public.t_branch b on b.branch_id = t.branch_id
  where t.academic_year = v_current_year
    and (p_region_id is null or b.region_id = p_region_id)
    and (p_branch_id is null or t.branch_id = p_branch_id);

  with
  months(month_label, month_number) as (
    values ('Jul',1),('Aug',2),('Sep',3),('Oct',4),('Nov',5),('Dec',6),
           ('Jan',7),('Feb',8),('Mar',9),('Apr',10),('May',11),('Jun',12)
  ),
  actual(month_label, revenue, transactions) as (
    select split_part(tx.month, ' ', 1), sum(tx.revenue), count(*)
    from public.t_revenue_txn tx
    join public.t_branch b on b.branch_id = tx.branch_id
      where tx.academic_year = v_current_year
      and tx.payment_date between v_start_date and v_end_date
      and (p_region_id is null or b.region_id = p_region_id)
      and (p_branch_id is null or tx.branch_id = p_branch_id)
    group by split_part(tx.month, ' ', 1)
  ),
  ly(month_label, revenue) as (
    select split_part(tx.month, ' ', 1), sum(tx.revenue)
    from public.t_revenue_txn tx
    join public.t_branch b on b.branch_id = tx.branch_id
      where v_ly_year is not null
      and tx.academic_year = v_ly_year
      and tx.payment_date between v_ly_start and v_ly_end
      and (p_region_id is null or b.region_id = p_region_id)
      and (p_branch_id is null or tx.branch_id = p_branch_id)
    group by split_part(tx.month, ' ', 1)
  ),
  l2y(month_label, revenue) as (
    select split_part(tx.month, ' ', 1), sum(tx.revenue)
    from public.t_revenue_txn tx
    join public.t_branch b on b.branch_id = tx.branch_id
      where v_l2y_year is not null
      and tx.academic_year = v_l2y_year
      and tx.payment_date between v_l2y_start and v_l2y_end
      and (p_region_id is null or b.region_id = p_region_id)
      and (p_branch_id is null or tx.branch_id = p_branch_id)
    group by split_part(tx.month, ' ', 1)
  ),
  targets(month_number, revenue) as (
    select t.month_number, sum(t.target_revenue)
    from public.t_revenue_monthly_target t
    join public.t_branch b on b.branch_id = t.branch_id
    where t.academic_year = v_current_year
      and (p_region_id is null or b.region_id = p_region_id)
      and (p_branch_id is null or t.branch_id = p_branch_id)
    group by t.month_number
  ),
  monthly as (
    select
      m.month_label,
      m.month_number,
      coalesce(a.revenue,0)::numeric current_revenue,
      coalesce(a.transactions,0)::integer current_transactions,
      case when v_ly_year is null then null else coalesce(y.revenue,0)::numeric end ly_revenue,
      case when v_l2y_year is null then null else coalesce(z.revenue,0)::numeric end l2y_revenue,
      coalesce(t.revenue,0)::numeric target_revenue
    from months m
    left join actual a on a.month_label = m.month_label
    left join ly y on y.month_label = m.month_label
    left join l2y z on z.month_label = m.month_label
    left join targets t on t.month_number = m.month_number
  ),
  cumulative as (
    select *,
      sum(current_revenue) over (order by month_number) current_cumulative_revenue,
      case when v_ly_year is null then null else sum(ly_revenue) over (order by month_number) end ly_cumulative_revenue,
      case when v_l2y_year is null then null else sum(l2y_revenue) over (order by month_number) end l2y_cumulative_revenue,
      sum(target_revenue) over (order by month_number) target_cumulative_revenue
    from monthly
  )
  select jsonb_build_object(
      'kpis', jsonb_build_object(
      'totalRevenue', v_current,
      'totalTransactions', coalesce((select sum(current_transactions) from monthly),0),
      'uniqueInvoices', 0,
      'activeBranches', 0,
      'activeAgents', 0,
      'knownSchools', 0,
      'averageOrderValue', 0,
      'nonBulkRevenue', 0,
      'nonBulkNewTransactions', 0,
      'targetAnnualRevenue', v_target,
      'achievement', case when v_target = 0 then null else v_current / v_target end,
      'varianceToTarget', v_current - v_target,
      'growthVsLy', case when v_ly = 0 then null else v_current / v_ly end,
      'growthVsL2y', case when v_l2y = 0 then null else v_current / v_l2y end
    ),
    'monthlyRevenue', coalesce((select jsonb_agg(jsonb_build_object('name', month_label, 'period', month_label, 'revenue', current_revenue, 'transactions', current_transactions) order by month_number) from cumulative), '[]'::jsonb),
    'monthlyRevenueComparison', jsonb_build_object(
      'currentAcademicYear', v_current_year,
      'previousAcademicYear', v_ly_year,
      'rows', coalesce((select jsonb_agg(jsonb_build_object(
        'month', month_label,
        'currentRevenue', current_revenue,
        'currentCumulativeRevenue', current_cumulative_revenue,
        'currentTransactions', current_transactions,
        'previousRevenue', ly_revenue,
        'previousCumulativeRevenue', ly_cumulative_revenue,
        'previousTransactions', null,
        'lastTwoYearsRevenue', l2y_revenue,
        'lastTwoYearsCumulativeRevenue', l2y_cumulative_revenue,
        'targetRevenue', target_revenue,
        'targetCumulativeRevenue', target_cumulative_revenue
      ) order by month_number) from cumulative), '[]'::jsonb)
    ),
    'filters', jsonb_build_object(
      'academicYears', (select coalesce(jsonb_agg(jsonb_build_object('id', academic_year, 'label', academic_year) order by academic_year desc),'[]'::jsonb) from public.t_academic_year),
      'regions', (select coalesce(jsonb_agg(jsonb_build_object('id', region_id::text, 'label', region_name) order by region_name),'[]'::jsonb) from public.t_region),
      'branches', (select coalesce(jsonb_agg(jsonb_build_object('id', branch_id::text, 'label', branch_name, 'regionId', region_id::text) order by branch_name),'[]'::jsonb) from public.t_branch where region_id is not null),
      'months', (select coalesce(jsonb_agg(jsonb_build_object('id', public.revenue_academic_month_label(month_number), 'label', public.revenue_academic_month_label(month_number)) order by month_number),'[]'::jsonb) from months)
    ),
    'regionalRevenue', '[]'::jsonb,
    'branchRevenue', '[]'::jsonb,
    'productRevenue', '[]'::jsonb,
    'paymentCategoryRevenue', '[]'::jsonb,
    'levelRevenue', '[]'::jsonb,
    'dataQuality', '[]'::jsonb,
    'recentTransactions', '[]'::jsonb,
    'agentPerformance', '[]'::jsonb
  )
  into v_result;

  return v_result;
end;
$$;

revoke execute on function public.get_revenue_dashboard_v2(text, integer, integer, text, date, date) from public;
grant execute on function public.get_revenue_dashboard_v2(text, integer, integer, text, date, date) to service_role;
