-- Weekly revenue targets for agent performance tracking.
create table if not exists public.t_agent_weekly_target (
  id bigint generated by default as identity primary key,
  agent_id integer not null,
  academic_year text not null,
  month text not null,
  week_start date not null,
  branch_id integer,
  target_revenue integer not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint t_agent_weekly_target_agent_id_fkey foreign key (agent_id)
    references public.t_agent (agent_id),
  constraint t_agent_weekly_target_academic_year_fkey foreign key (academic_year)
    references public.t_academic_year (academic_year),
  constraint t_agent_weekly_target_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_agent_weekly_target_week_start_monday_check
    check (extract(isodow from week_start) = 1),
  constraint t_agent_weekly_target_month_format_check
    check (month ~ '^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) [0-9]{4}$'),
  constraint t_agent_weekly_target_branch_excluded_check
    check (branch_id is null or branch_id <> 100),
  constraint t_agent_weekly_target_revenue_non_negative
    check (target_revenue >= 0),
  constraint t_agent_weekly_target_agent_week_unique
    unique (agent_id, week_start)
);

create index if not exists t_agent_weekly_target_academic_month_idx
  on public.t_agent_weekly_target (academic_year, month);
create index if not exists t_agent_weekly_target_agent_week_idx
  on public.t_agent_weekly_target (agent_id, week_start);
create index if not exists t_agent_weekly_target_branch_id_idx
  on public.t_agent_weekly_target (branch_id);

alter table public.t_agent_weekly_target enable row level security;

drop trigger if exists set_t_agent_weekly_target_updated_at
  on public.t_agent_weekly_target;
create trigger set_t_agent_weekly_target_updated_at
before update on public.t_agent_weekly_target
for each row execute function public.set_updated_at();

drop policy if exists "authenticated can read agent weekly targets"
  on public.t_agent_weekly_target;
create policy "authenticated can read agent weekly targets"
  on public.t_agent_weekly_target for select
  to authenticated
  using (true);

drop policy if exists "service role can manage agent weekly targets"
  on public.t_agent_weekly_target;
create policy "service role can manage agent weekly targets"
  on public.t_agent_weekly_target for all
  to service_role
  using (true)
  with check (true);
