-- Rows that could not be imported because required agent/branch fields were incomplete.
create table if not exists public.t_revenue_upload_issue (
  id bigint generated by default as identity primary key,
  batch_id uuid not null,
  source_row integer not null,
  start_date date not null,
  raw_row jsonb not null,
  missing_fields text[] not null default '{}',
  status text not null default 'pending',
  error_message text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  resolved_at timestamp with time zone,
  constraint t_revenue_upload_issue_status_check
    check (status in ('pending', 'uploaded', 'failed')),
  constraint t_revenue_upload_issue_batch_row_unique
    unique (batch_id, source_row)
);

create index if not exists t_revenue_upload_issue_status_idx
  on public.t_revenue_upload_issue (status, created_at desc);

alter table public.t_revenue_upload_issue enable row level security;

drop trigger if exists set_t_revenue_upload_issue_updated_at
  on public.t_revenue_upload_issue;
create trigger set_t_revenue_upload_issue_updated_at
before update on public.t_revenue_upload_issue
for each row execute function public.set_updated_at();

drop policy if exists "service role can manage revenue upload issues"
  on public.t_revenue_upload_issue;
create policy "service role can manage revenue upload issues"
  on public.t_revenue_upload_issue for all
  to service_role
  using (true)
  with check (true);
